### ISSUE TITLE
Look into how many sites each potential filter would remove (i.e., site type, last 24 hours, last 20 years, <5yrs, etc.)

### ISSUE THREAD

**Issue by NorahMaki** [18F/usgs-water#23]
from @csnowUSGS 

Surface water https://waterdata.usgs.gov/nwis/sw

- Current conditions (last 120 days): 10,500
- Historical: 17,400
- Field measurements: 71,500
- Last 24 hours: TBD

Ground water: https://waterdata.usgs.gov/nwis/gw
	Current conditions (last 18 mos): 1,800
	Historical: 5,000
	Field measurements: 900,000
	Last 24 hours (sampled or continuous): TBD

Spring:https://waterdata.usgs.gov/networks/SPR/ (122)
Active: ~500
Atmospheric: 
Active: ~500 eyeballing nwis mapper

Other: 
Active: ~100 eyeballing nwis mapper

 
Water quality: https://waterdata.usgs.gov/nwis/qw
Cc: 2,200
Historical: 2,200
Field: 422,500

 A site is considered active if: (1) it has collected time-series (automated) data within the last 183 days (6 months), or (2) it has collected discrete (manually collected) data within 397 days (13 months). If it does not meet these criteria, it is considered inactive. Some exceptions apply. For example, a site may also be shown as active if it is part of an ongoing occasional data-collection program. If a site is flagged by a USGS water science center as discontinued, it will show as inactive regardless of how recent data may be. A USGS science center can also flag a new site as active even if it has not collected any data. This control allows a user to select a broad category of sites to view, and is useful for simplifying a view in areas with a high density of sites. The default selection is Active sites.

**Comment by srgregory-po** [comment]
# of sites with Discharge:
Daily values: 27,324 sites
Instantaneous: 13,570 sites

# of sites changed in the last day:
115,778 sites*

* Note about this: we are working in the databases right now, so we are going to see a higher number of changed data than normal.  This is a good example of our backend impact on this filter.

**Comment by NorahMaki** [comment]
Updated doc here: https://docs.google.com/document/d/11Ww1njoPpldbmBiK_P-sY01lU4rVz0UKKA27KlFfFyc/edit#
