### ISSUE TITLE
Compile list of different "admin levels" and how they do/could  nest (i.e., state, HUC, watershed, network, self-selected boundary)

### ISSUE THREAD

**Issue by amymok** [18F/usgs-water#4]

**Comment by NorahMaki** [comment]
@srgregory-po to share list; 
@NorahMaki to set up meeting/working session to organize these in mural

**Comment by NorahMaki** [comment]
@NorahMaki to set up 30mins for early next week to build out the list in https://docs.google.com/spreadsheets/d/1uPMef5SHA3RCX3Ir_LfHtkbnPARpXQmL6BFKQcrGRCM/edit#gid=266744667

**Comment by NorahMaki** [comment]
List updated in https://docs.google.com/spreadsheets/d/1uPMef5SHA3RCX3Ir_LfHtkbnPARpXQmL6BFKQcrGRCM/edit#gid=0

Decision made to use State, County, Bounding box for geographic filters for now. As we test, will aim to learn more about whether people need HUC and/or Network filters as well.
