### ISSUE TITLE
Look at standards/inspiration for displaying monitoring sites and site types

### ISSUE THREAD

**Issue by amymok** [18F/usgs-water#9]
Mural with references from @csnowUSGS conversations with USGS SMEs, https://app.mural.co/t/usgsiow1665/m/usgsiow1665/1591911540148/d8a36f04545f91e163cd30aa681d70b6b86dcd81

**Comment by NorahMaki** [comment]
@csnowUSGS to set up meeting with USGS publications person

**Comment by csnowUSGS** [comment]
Mural of existing print map guidance and current mappers: 
https://app.mural.co/t/usgsiow1665/m/usgsiow1665/1591911540148/d8a36f04545f91e163cd30aa681d70b6b86dcd81

**Comment by NorahMaki** [comment]
USGS site symbology (from @csnowUSGS ) https://maps.waterdata.usgs.gov/mapper/instructions.html#:~:text=Selecting%20Sites%20to%20Include,types%20and%2042%20secondary%20types.
